"use client";
import Link from "next/link"; import {useState} from "react"; import {Header} from "./components/Header"; import {ArticleCard} from "./components/ArticleCard"; import {AdSlot} from "./components/AdSlot"; import {FlashTicker} from "./components/FlashTicker"; import {HeroSlider} from "./components/HeroSlider"; import {articles,briefs,markets,regions} from "../lib/mock-data";
export default function Home(){const[email,setEmail]=useState("");const[ok,setOk]=useState(false);return <main className="edition-home"><Header/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"NewsMediaOrganization",name:"L’Économiste de la Côte d’Ivoire",url:"https://leconomistedelacotedivoire.com",areaServed:{"@type":"Country",name:"Côte d’Ivoire"}})}}/><FlashTicker/>
<div className="home-dateline"><div className="shell"><span>JEUDI 13 AOÛT 2026</span><strong>ÉDITION NATIONALE</strong><span>ABIDJAN · 26°C</span></div></div>
<section className="ad-leaderboard shell"><AdSlot format="Billboard · 970 × 250" title="La première impression compte." copy="Positionnez votre marque au sommet de l’actualité économique ivoirienne." variant="dark"/></section>
<section className="front-page shell"><div className="front-page__title"><span>L’ESSENTIEL DU JOUR</span><h1>La Côte d’Ivoire <em>en mouvement.</em></h1><p>Économie, pouvoir, entreprises et territoires : une lecture exigeante de ce qui transforme le pays.</p></div><HeroSlider items={articles.slice(0,4)}/><div className="front-page__rail">{articles.slice(4,6).map((a,i)=><article key={a.slug}><span>0{i+1} · {a.region}</span><h3><Link href={`/articles/${a.slug}`}>{a.title}</Link></h3><p>{a.excerpt}</p></article>)}<AdSlot format="Pavé · 300 × 250" title="Votre campagne, au cœur du débat." variant="dark"/></div></section>
<div className="market-strip market-strip--premium"><div className="shell market-strip__inner"><span className="market-title">TABLEAU DE BORD</span>{markets.map(m=><span key={m.name}><b>{m.name}</b> {m.value} <i className="up">{m.change}</i></span>)}</div></div>
<section className="section shell newsroom-section"><div className="editorial-heading"><span>01</span><div><small>LE FIL IVOIRIEN</small><h2>Ce qu’il faut savoir maintenant</h2></div><Link href="/explorer">Toute l’actualité →</Link></div><div className="newsroom-grid">{articles.slice(2,10).map(a=><ArticleCard key={a.slug} article={a}/>)}</div></section>
<section className="ad-inventory shell"><AdSlot format="Super leaderboard · 970 × 180" title="Un rendez-vous quotidien avec l’économie ivoirienne." variant="light"/><div><AdSlot format="Rectangle · 300 × 250" title="Financez votre visibilité." variant="dark"/><AdSlot format="Rectangle · 300 × 250" title="Parlez aux bâtisseurs." variant="dark"/><AdSlot format="Rectangle · 300 × 250" title="Rayonnez dans les régions." variant="dark"/></div></section>
<section className="section dark-report"><div className="shell"><div className="editorial-heading editorial-heading--dark"><span>02</span><div><small>GRAND ANGLE</small><h2>Économie réelle</h2></div><Link href="/categorie/economie">Voir les analyses →</Link></div><div className="report-grid"><ArticleCard article={articles[8]} large/><div className="report-list">{articles.slice(9,15).map((a,i)=><Link href={`/articles/${a.slug}`} key={a.slug}><span>{String(i+1).padStart(2,"0")}</span><div><small>{a.category} · {a.region}</small><strong>{a.title}</strong></div><b>↗</b></Link>)}</div><AdSlot format="Half page · 300 × 600" title="Une audience qui décide." copy="Visibilité et crédibilité auprès des acteurs économiques ivoiriens." variant="dark"/></div></div></section>
<section className="section shell brief-section"><div className="editorial-heading"><span>03</span><div><small>EN CONTINU</small><h2>Les nouvelles en bref</h2></div><Link href="/explorer">Voir le fil complet →</Link></div><div className="brief-stream">{briefs.map((b,i)=><article key={b.title}><span>{String(i+1).padStart(2,"0")}</span><div><small>{b.category} · {b.region}</small><h3>{b.title}</h3></div><time>{15-Math.floor(i/2)}:{i%2?"18":"42"}</time></article>)}</div></section>
<section className="native-campaign shell"><AdSlot format="Contenu partenaire · Native premium" title="Bâtir la Côte d’Ivoire de demain" copy="Un dossier de marque immersif, intégré avec transparence dans l’expérience éditoriale." variant="native"/></section>
<section className="section shell"><div className="editorial-heading"><span>04</span><div><small>DU NORD AU LITTORAL</small><h2>Nos territoires</h2></div><Link href="/regions">Toutes les régions →</Link></div><div className="territory-ticker">{regions.map((r,i)=><Link href={`/regions#${r.toLowerCase()}`} key={r}><span>{String(i+1).padStart(2,"0")}</span><strong>{r}</strong><small>Voir l’actualité →</small></Link>)}</div></section>
<section className="sponsor-wall"><div className="shell"><div><span>PARTENAIRES & ANNONCEURS</span><strong>Votre marque ici</strong><strong>Votre campagne ici</strong><strong>Votre institution ici</strong><strong>Votre événement ici</strong></div><p>Emplacements de démonstration — aucune marque réelle n’est associée à cette maquette.</p></div></section>
<section className="advertiser-hub"><div className="shell advertiser-hub__inner"><div><span>MEDIA KIT 2026</span><h2>Votre marque mérite un contexte de confiance.</h2><p>Display premium, formats natifs, newsletters, podcasts et opérations spéciales pour le marché ivoirien.</p><Link href="/informations">Parler à notre régie publicitaire →</Link></div><div className="advertiser-metrics"><div><strong>42 k</strong><span>lecteurs mensuels mock</span></div><div><strong>68 %</strong><span>décideurs & entrepreneurs</span></div><div><strong>8</strong><span>territoires couverts</span></div><small>Données de démonstration.</small></div></div></section>
<section className="newsletter-section newsletter-section--premium"><div className="shell newsletter-inner"><div><span>LA MATINALE IVOIRIENNE</span><h2>Une longueur d’avance.</h2><p>Une sélection concise envoyée avant 7 h.</p></div>{ok?<strong className="newsletter-success">✓ Inscription enregistrée.</strong>:<form onSubmit={e=>{e.preventDefault();localStorage.setItem("newsletter-email",email);setOk(true)}}><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Votre adresse e-mail"/><button>S’inscrire gratuitement</button><small>Mode maquette.</small></form>}</div></section>
</main>}
