export type Article = { slug:string; title:string; excerpt:string; category:string; region:string; author:string; date:string; readTime:string; image:string; featured?:boolean; views:number; body:string[] };

export const categories = ["Économie","Politique","Entreprises","Finance & BRVM","Agriculture & Cacao","Énergie & Mines","Technologie","Société","Culture","Sport","Opinions"];
export const regions = ["Abidjan","Yamoussoukro","Bouaké","San-Pédro","Korhogo","Man","Daloa","Grand-Bassam"];

export const articles: Article[] = [
 {slug:"abidjan-hub-financier-afrique-ouest",title:"Abidjan consolide sa place de hub financier de l’Afrique de l’Ouest",excerpt:"Banques, fintech et marché régional : les leviers qui renforcent l’attractivité de la capitale économique ivoirienne.",category:"Finance & BRVM",region:"Abidjan",author:"Aïssata Koné",date:"13 août 2026",readTime:"8 min",image:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1800&q=88",featured:true,views:12840,body:["Au Plateau, les sièges bancaires et les nouveaux acteurs de la finance numérique composent un écosystème en pleine accélération.","La présence de la BRVM, d’institutions régionales et d’un tissu entrepreneurial dense permet à Abidjan de jouer un rôle central dans la circulation des capitaux en zone UEMOA.","Le prochain défi sera d’orienter davantage ces financements vers les PME ivoiriennes, l’industrie et les emplois qualifiés."]},
 {slug:"cacao-transformation-locale-san-pedro",title:"Cacao : San-Pédro accélère la transformation locale",excerpt:"Les investissements industriels veulent créer plus de valeur en Côte d’Ivoire avant l’exportation.",category:"Agriculture & Cacao",region:"San-Pédro",author:"Kouadio N’Guessan",date:"13 août 2026",readTime:"6 min",image:"https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=1400&q=85",featured:true,views:10420,body:["Premier producteur mondial de cacao, la Côte d’Ivoire veut transformer une part croissante de ses fèves sur place.","À San-Pédro, de nouvelles capacités de broyage soutiennent l’emploi industriel et la montée en compétence des entreprises locales.","La rémunération des producteurs et la traçabilité restent au cœur de la compétitivité de la filière."]},
 {slug:"bouake-pme-industrie",title:"À Bouaké, les PME industrielles gagnent du terrain",excerpt:"Agroalimentaire, logistique et services structurent un nouveau cycle d’investissement dans le centre du pays.",category:"Entreprises",region:"Bouaké",author:"Mariam Traoré",date:"12 août 2026",readTime:"5 min",image:"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=85",views:8210,body:["Bouaké retrouve progressivement sa fonction de carrefour économique national.","Les entrepreneurs locaux investissent dans la transformation agricole, les services et la logistique.","L’accès au crédit et au foncier industriel demeure déterminant pour consolider cette dynamique."]},
 {slug:"energie-solaire-korhogo",title:"Korhogo mise sur le solaire pour soutenir sa croissance",excerpt:"Le nord ivoirien développe de nouvelles capacités énergétiques au service des ménages et des entreprises.",category:"Énergie & Mines",region:"Korhogo",author:"Fatou Diabaté",date:"12 août 2026",readTime:"7 min",image:"https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1400&q=85",views:7560,body:["Le potentiel solaire du nord ivoirien attire de nouveaux projets énergétiques.","Ces installations doivent sécuriser l’approvisionnement des villes et accompagner le développement industriel régional.","La formation de techniciens locaux constitue un enjeu essentiel pour pérenniser les équipements."]},
 {slug:"startup-ivoiriennes-paiement",title:"Les startups ivoiriennes réinventent le paiement de proximité",excerpt:"Une génération de jeunes entreprises simplifie les transactions des commerçants et des petites entreprises.",category:"Technologie",region:"Abidjan",author:"Sarah Yao",date:"11 août 2026",readTime:"4 min",image:"https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1400&q=85",views:9320,body:["Le paiement mobile est devenu une infrastructure quotidienne de l’économie ivoirienne.","Les jeunes pousses développent des outils adaptés aux réalités des commerçants, artisans et PME.","La confiance, la cybersécurité et l’interopérabilité détermineront la prochaine phase de croissance."]},
 {slug:"yamoussoukro-politiques-publiques",title:"Yamoussoukro prépare une nouvelle génération de services publics",excerpt:"Numérisation, proximité et mesure de la performance sont au programme des administrations.",category:"Politique",region:"Yamoussoukro",author:"Jean-Marc Koffi",date:"10 août 2026",readTime:"7 min",image:"https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1400&q=85",views:6740,body:["La modernisation de l’État doit rapprocher les démarches administratives des citoyens.","Plusieurs programmes misent sur le numérique, la simplification et la transparence.","Leur succès dépendra de la qualité du service dans toutes les régions du pays."]},
 {slug:"grand-bassam-tourisme-culture",title:"Grand-Bassam transforme son patrimoine en moteur économique",excerpt:"Culture, tourisme et entrepreneuriat créatif donnent un nouvel élan à la ville historique.",category:"Culture",region:"Grand-Bassam",author:"Grâce Assi",date:"9 août 2026",readTime:"6 min",image:"https://images.unsplash.com/photo-1566438480900-0609be27a4be?auto=format&fit=crop&w=1400&q=85",views:5880,body:["Grand-Bassam dispose d’un patrimoine architectural et culturel unique en Côte d’Ivoire.","Artisans, restaurateurs et opérateurs touristiques construisent une offre plus structurée.","La préservation du littoral reste indispensable pour assurer un développement durable."]},
 {slug:"diaspora-investissement-cote-ivoire",title:"Diaspora : de nouveaux outils pour investir en Côte d’Ivoire",excerpt:"Épargne, immobilier productif et capital-investissement rapprochent les Ivoiriens de l’étranger des projets locaux.",category:"Économie",region:"Abidjan",author:"Aïssata Koné",date:"8 août 2026",readTime:"5 min",image:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=85",views:11100,body:["La diaspora ivoirienne recherche des instruments plus transparents pour financer l’économie nationale.","Des plateformes et véhicules d’investissement apparaissent pour structurer cette demande.","La qualité de l’information financière sera déterminante pour installer la confiance."]},
];

export const getArticle=(slug:string)=>articles.find(a=>a.slug===slug);
export const markets=[{name:"BRVM Composite",value:"335,18",change:"+0,42 %"},{name:"BRVM 30",value:"168,74",change:"+0,31 %"},{name:"EUR/XOF",value:"655,96",change:"0,00 %"},{name:"Cacao",value:"7 842 $",change:"+1,16 %"}];
