export type Article = { slug:string; title:string; excerpt:string; category:string; region:string; author:string; date:string; readTime:string; image:string; featured?:boolean; views:number; body:string[]; essentiel?:string[]; pourquoi?:string };

export const categories = ["Économie","Politique","Entreprises","Finance & BRVM","Agriculture & Cacao","Énergie & Mines","Technologie","Société","Culture","Sport","Opinions","Événements"];
export const regions = ["Lagunes","Comoé","Bas-Sassandra","Gôh-Djiboua","Sassandra-Marahoué","Lacs","Vallée du Bandama","Montagnes","Savanes","Zanzan","Denguélé","Woroba"];

export const articles: Article[] = [
 {slug:"abidjan-hub-financier-afrique-ouest",title:"Abidjan consolide sa place de hub financier de l’Afrique de l’Ouest",excerpt:"Banques, fintech et marché régional : les leviers qui renforcent l’attractivité de la capitale économique ivoirienne.",category:"Finance & BRVM",region:"Lagunes",author:"Aïssata Koné",date:"13 août 2026",readTime:"8 min",image:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1800&q=88",featured:true,views:12840,body:["Au Plateau, les sièges bancaires et les nouveaux acteurs de la finance numérique composent un écosystème en pleine accélération.","La présence de la BRVM, d’institutions régionales et d’un tissu entrepreneurial dense permet à Abidjan de jouer un rôle central dans la circulation des capitaux en zone UEMOA.","Le prochain défi sera d’orienter davantage ces financements vers les PME ivoiriennes, l’industrie et les emplois qualifiés."]},
 {slug:"cacao-transformation-locale-san-pedro",title:"Cacao : San-Pédro accélère la transformation locale",excerpt:"Les investissements industriels veulent créer plus de valeur en Côte d’Ivoire avant l’exportation.",category:"Agriculture & Cacao",region:"Bas-Sassandra",author:"Kouadio N’Guessan",date:"13 août 2026",readTime:"6 min",image:"https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=1400&q=85",featured:true,views:10420,body:["Premier producteur mondial de cacao, la Côte d’Ivoire veut transformer une part croissante de ses fèves sur place.","À San-Pédro, de nouvelles capacités de broyage soutiennent l’emploi industriel et la montée en compétence des entreprises locales.","La rémunération des producteurs et la traçabilité restent au cœur de la compétitivité de la filière."]},
 {slug:"bouake-pme-industrie",title:"À Bouaké, les PME industrielles gagnent du terrain",excerpt:"Agroalimentaire, logistique et services structurent un nouveau cycle d’investissement dans le centre du pays.",category:"Entreprises",region:"Vallée du Bandama",author:"Mariam Traoré",date:"12 août 2026",readTime:"5 min",image:"https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=85",views:8210,body:["Bouaké retrouve progressivement sa fonction de carrefour économique national.","Les entrepreneurs locaux investissent dans la transformation agricole, les services et la logistique.","L’accès au crédit et au foncier industriel demeure déterminant pour consolider cette dynamique."]},
 {slug:"energie-solaire-korhogo",title:"Korhogo mise sur le solaire pour soutenir sa croissance",excerpt:"Le nord ivoirien développe de nouvelles capacités énergétiques au service des ménages et des entreprises.",category:"Énergie & Mines",region:"Savanes",author:"Fatou Diabaté",date:"12 août 2026",readTime:"7 min",image:"https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1400&q=85",views:7560,body:["Le potentiel solaire du nord ivoirien attire de nouveaux projets énergétiques.","Ces installations doivent sécuriser l’approvisionnement des villes et accompagner le développement industriel régional.","La formation de techniciens locaux constitue un enjeu essentiel pour pérenniser les équipements."]},
 {slug:"startup-ivoiriennes-paiement",title:"Les startups ivoiriennes réinventent le paiement de proximité",excerpt:"Une génération de jeunes entreprises simplifie les transactions des commerçants et des petites entreprises.",category:"Technologie",region:"Lagunes",author:"Sarah Yao",date:"11 août 2026",readTime:"4 min",image:"https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1400&q=85",views:9320,body:["Le paiement mobile est devenu une infrastructure quotidienne de l’économie ivoirienne.","Les jeunes pousses développent des outils adaptés aux réalités des commerçants, artisans et PME.","La confiance, la cybersécurité et l’interopérabilité détermineront la prochaine phase de croissance."]},
 {slug:"yamoussoukro-politiques-publiques",title:"Yamoussoukro prépare une nouvelle génération de services publics",excerpt:"Numérisation, proximité et mesure de la performance sont au programme des administrations.",category:"Politique",region:"Lacs",author:"Jean-Marc Koffi",date:"10 août 2026",readTime:"7 min",image:"https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1400&q=85",views:6740,body:["La modernisation de l’État doit rapprocher les démarches administratives des citoyens.","Plusieurs programmes misent sur le numérique, la simplification et la transparence.","Leur succès dépendra de la qualité du service dans toutes les régions du pays."]},
 {slug:"grand-bassam-tourisme-culture",title:"Grand-Bassam transforme son patrimoine en moteur économique",excerpt:"Culture, tourisme et entrepreneuriat créatif donnent un nouvel élan à la ville historique.",category:"Culture",region:"Comoé",author:"Grâce Assi",date:"9 août 2026",readTime:"6 min",image:"https://images.unsplash.com/photo-1566438480900-0609be27a4be?auto=format&fit=crop&w=1400&q=85",views:5880,body:["Grand-Bassam dispose d’un patrimoine architectural et culturel unique en Côte d’Ivoire.","Artisans, restaurateurs et opérateurs touristiques construisent une offre plus structurée.","La préservation du littoral reste indispensable pour assurer un développement durable."]},
 {slug:"diaspora-investissement-cote-ivoire",title:"Diaspora : de nouveaux outils pour investir en Côte d’Ivoire",excerpt:"Épargne, immobilier productif et capital-investissement rapprochent les Ivoiriens de l’étranger des projets locaux.",category:"Économie",region:"Lagunes",author:"Aïssata Koné",date:"8 août 2026",readTime:"5 min",image:"https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=85",views:11100,body:["La diaspora ivoirienne recherche des instruments plus transparents pour financer l’économie nationale.","Des plateformes et véhicules d’investissement apparaissent pour structurer cette demande.","La qualité de l’information financière sera déterminante pour installer la confiance."]},
 {slug:"metro-abidjan-mobilite-emplois",title:"Métro d’Abidjan : les quartiers se préparent à une nouvelle mobilité",excerpt:"Entre emplois, commerces et correspondances, le futur axe ferroviaire transforme déjà les stratégies urbaines.",category:"Société",region:"Lagunes",author:"Nadia Bamba",date:"7 août 2026",readTime:"7 min",image:"https://images.unsplash.com/photo-1516939884455-1445c8652f83?auto=format&fit=crop&w=1600&q=86",views:9870,body:["Le métro doit relier plus rapidement plusieurs bassins de vie et d’emploi de l’agglomération.","Autour des stations, les collectivités anticipent de nouveaux besoins en voirie, sécurité et commerce.","L’enjeu sera de rendre les correspondances simples avec les bus, taxis et autres transports collectifs."]},
 {slug:"brvm-pme-ivoiriennes-capital",title:"BRVM : les PME ivoiriennes explorent de nouvelles voies de financement",excerpt:"Le marché régional veut rapprocher l’épargne disponible des entreprises qui préparent leur changement d’échelle.",category:"Finance & BRVM",region:"Lagunes",author:"Serge Kouamé",date:"7 août 2026",readTime:"8 min",image:"https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1600&q=86",views:8940,body:["L’ouverture du capital peut offrir aux PME une alternative au crédit bancaire classique.","Elle exige cependant une gouvernance renforcée et une information financière régulière.","Les investisseurs suivent particulièrement les secteurs de l’agro-industrie, de la logistique et du numérique."]},
 {slug:"anacarde-bondoukou-transformation",title:"À Bondoukou, l’anacarde cherche davantage de valeur locale",excerpt:"Producteurs et transformateurs veulent conserver une part plus importante des revenus de la filière dans le pays.",category:"Agriculture & Cacao",region:"Zanzan",author:"Moussa Ouattara",date:"6 août 2026",readTime:"6 min",image:"https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1600&q=86",views:7210,body:["La noix de cajou soutient les revenus de milliers de familles du nord-est ivoirien.","Les nouvelles unités locales cherchent à mieux valoriser la récolte et ses sous-produits.","La qualité, le stockage et l’accès à l’énergie détermineront leur compétitivité."]},
 {slug:"port-sassandra-economie-bleue",title:"Sassandra construit sa stratégie autour de l’économie bleue",excerpt:"Pêche, chaîne du froid et tourisme durable peuvent créer de nouvelles activités sur le littoral.",category:"Économie",region:"Bas-Sassandra",author:"Grâce Assi",date:"6 août 2026",readTime:"6 min",image:"https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1600&q=86",views:6480,body:["Le littoral de Sassandra offre un potentiel économique encore peu structuré.","Les professionnels demandent des équipements adaptés pour conserver et transporter les produits de la mer.","La protection des plages et des mangroves doit accompagner tout nouveau développement."]},
 {slug:"odienne-numerique-services-ruraux",title:"Odienné teste des services numériques adaptés aux zones rurales",excerpt:"Santé, démarches administratives et commerce profitent de solutions pensées pour les longues distances.",category:"Technologie",region:"Denguélé",author:"Sarah Yao",date:"5 août 2026",readTime:"5 min",image:"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1600&q=86",views:5870,body:["La distance ne doit plus empêcher l’accès aux services essentiels.","Des entrepreneurs expérimentent des points connectés et des applications peu gourmandes en données.","La couverture réseau et l’accompagnement des usagers restent les premières conditions de réussite."]},
 {slug:"gagnoa-cafe-cacao-cooperatives",title:"À Gagnoa, les coopératives modernisent le suivi du café-cacao",excerpt:"Traçabilité, données agricoles et services partagés renforcent progressivement l’organisation des producteurs.",category:"Agriculture & Cacao",region:"Gôh-Djiboua",author:"Kouadio N’Guessan",date:"5 août 2026",readTime:"7 min",image:"https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1600&q=86",views:7760,body:["Les coopératives occupent une place centrale entre producteurs, acheteurs et organismes de régulation.","Les outils numériques améliorent le suivi des volumes, des parcelles et des paiements.","Cette modernisation doit aussi produire des services concrets pour les familles rurales."]},
 {slug:"man-tourisme-montagnes-emplois",title:"Man veut transformer son patrimoine naturel en emplois durables",excerpt:"Guides, hébergements et artisanat local structurent une offre touristique tournée vers les montagnes.",category:"Culture",region:"Montagnes",author:"Élodie Guei",date:"4 août 2026",readTime:"6 min",image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=86",views:8350,body:["Les paysages de l’ouest ivoirien attirent une clientèle nationale et régionale croissante.","Les acteurs locaux souhaitent professionnaliser l’accueil sans dénaturer les sites.","Formation des guides, mobilité et promotion commune figurent parmi les chantiers prioritaires."]},
 {slug:"bouake-basketball-economie-sport",title:"Bouaké mise sur le sport pour animer son économie locale",excerpt:"Compétitions, équipements et petites entreprises composent un écosystème qui dépasse les terrains.",category:"Sport",region:"Vallée du Bandama",author:"Arnaud Kassi",date:"4 août 2026",readTime:"5 min",image:"https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1600&q=86",views:6920,body:["Les événements sportifs attirent des visiteurs et créent une activité temporaire importante.","Des entrepreneurs se positionnent dans l’équipement, la restauration et la communication.","Une programmation régulière permettrait de stabiliser ces retombées tout au long de l’année."]},
 {slug:"san-pedro-port-logistique-regionale",title:"Le port de San-Pédro renforce ses connexions avec l’hinterland",excerpt:"Routes, entrepôts et services numériques doivent fluidifier les échanges avec les zones de production.",category:"Entreprises",region:"Bas-Sassandra",author:"Mariam Traoré",date:"3 août 2026",readTime:"8 min",image:"https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1600&q=86",views:9180,body:["Le port constitue une infrastructure stratégique pour les exportations ivoiriennes.","Sa performance dépend aussi de la qualité des corridors qui le relient aux bassins agricoles et miniers.","La numérisation documentaire peut réduire les délais et améliorer la visibilité des marchandises."]},
 {slug:"yamoussoukro-eau-urbanisme",title:"Yamoussoukro place l’eau au centre de sa planification urbaine",excerpt:"Croissance démographique et nouveaux quartiers imposent d’anticiper les réseaux et la protection des ressources.",category:"Politique",region:"Lacs",author:"Jean-Marc Koffi",date:"3 août 2026",readTime:"7 min",image:"https://images.unsplash.com/photo-1548839140-29a749e1cf4d?auto=format&fit=crop&w=1600&q=86",views:5690,body:["La capitale politique doit adapter ses réseaux à l’extension progressive de la ville.","Les investissements concernent la production, le stockage et la distribution de l’eau potable.","Une coordination étroite avec l’urbanisme permettra d’éviter des infrastructures trop rapidement saturées."]},
 {slug:"daloa-femmes-entrepreneures-agro",title:"À Daloa, les entrepreneures accélèrent dans l’agroalimentaire",excerpt:"Transformation, emballage et distribution ouvrent de nouveaux marchés aux entreprises portées par des femmes.",category:"Entreprises",region:"Sassandra-Marahoué",author:"Nadia Bamba",date:"2 août 2026",readTime:"6 min",image:"https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=1600&q=86",views:7430,body:["Les produits agricoles locaux offrent de nombreuses possibilités de transformation.","Des dirigeantes investissent dans la qualité, les marques et des réseaux de distribution plus formels.","L’accès aux équipements et au financement de croissance demeure leur principal défi."]},
 {slug:"grand-bassam-littoral-climat",title:"Grand-Bassam adapte son littoral aux risques climatiques",excerpt:"Protection côtière, patrimoine et activités touristiques doivent avancer dans une stratégie commune.",category:"Société",region:"Comoé",author:"Élodie Guei",date:"2 août 2026",readTime:"8 min",image:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=86",views:8120,body:["L’érosion côtière menace à la fois les quartiers, les activités et le patrimoine historique.","Les réponses techniques doivent intégrer les usages quotidiens du littoral.","Habitants, scientifiques et opérateurs économiques demandent une planification suivie dans le temps."]},
 {slug:"opinion-pme-commande-publique",title:"Opinion : la commande publique peut devenir un accélérateur pour les PME",excerpt:"Des procédures plus lisibles et des délais maîtrisés renforceraient le tissu productif ivoirien.",category:"Opinions",region:"Lagunes",author:"Dr Aminata Fofana",date:"1 août 2026",readTime:"9 min",image:"https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1600&q=86",views:10340,body:["La commande publique représente un levier économique majeur lorsqu’elle reste accessible aux entreprises locales.","La transparence des calendriers et la réduction des délais de paiement peuvent soutenir leur trésorerie.","L’objectif n’est pas de réduire les exigences, mais de rendre les règles plus prévisibles et plus inclusives."]},
];

export const getArticle=(slug:string)=>articles.find(a=>a.slug===slug);

// L'essentiel en 3 points — fourni par l'article ou dérivé du contenu
const firstSentence=(text:string)=>{const s=(text||"").split(/(?<=[.!?])\s/)[0]||text||"";return s.trim()};
export const articleEssentiel=(a:Article):string[]=>{
  if(a.essentiel&&a.essentiel.length)return a.essentiel.slice(0,3);
  return [a.excerpt, firstSentence(a.body[1]||""), firstSentence(a.body[2]||"")].map(s=>s.trim()).filter(Boolean).slice(0,3);
};
// Pourquoi ça compte — impact concret
export const articlePourquoi=(a:Article):string=>a.pourquoi
  ??`Au-delà du fait, cette information pèse sur les décisions des citoyens, des entreprises et des acteurs publics concernés par ${a.category.toLowerCase()} en Côte d’Ivoire.`;

// Paragraphes de contexte (maquette) pour étoffer la lecture
export const articleContext=(a:Article):string[]=>{
  const cat=a.category.toLowerCase();
  return [
    `Dans la région des ${a.region}, cette évolution reflète une tendance de fond que suivent de près les acteurs concernés par ${cat} en Côte d’Ivoire. Plusieurs observateurs y voient un signal de la transformation économique et sociale en cours dans le pays.`,
    `Pour les Ivoiriens directement concernés, l’enjeu est très concret : emplois, revenus, accès aux services et qualité de vie dépendent en partie de la manière dont ce dossier sera piloté dans les prochains mois. Les décideurs locaux comme nationaux sont attendus sur des résultats mesurables.`,
    `La rédaction de L’Économiste continuera de documenter les prochaines étapes de ce dossier, en gardant une priorité constante : mesurer l’impact réel pour les citoyens, les entreprises et les institutions de Côte d’Ivoire.`,
  ];
};

// Sondage contextuel par rubrique
export const pollFor=(category:string):{question:string;options:string[]}=>{
  const map:Record<string,{question:string;options:string[]}>={
    "Politique":{question:"Cette décision politique va-t-elle dans le bon sens ?",options:["Oui","Non","Sans avis"]},
    "Sport":{question:"Les Éléphants iront-ils au bout de la compétition ?",options:["Oui, sans problème","Ce sera serré","J’en doute"]},
    "Économie":{question:"Ressentez-vous cette dynamique économique dans votre quotidien ?",options:["Oui, nettement","Un peu","Pas du tout"]},
    "Société":{question:"Cette évolution améliore-t-elle la vie des Ivoiriens ?",options:["Oui","Partiellement","Non"]},
  };
  return map[category]??{question:"Que pensez-vous de cette information ?",options:["Positif","Mitigé","Négatif"]};
};

// Fil « En direct » — actualité chaude horodatée, tous sujets. Chaque brève renvoie vers un article cohérent.
export type LiveEntry={time:string;label:string;region?:string;title:string;text:string;urgent?:boolean;slug:string};
export const liveHref=(e:LiveEntry):string=>`/articles/${e.slug}`;
export const liveImage=(e:LiveEntry):string=>getArticle(e.slug)?.image??"";
export const liveFeed:LiveEntry[]=[
 {time:"16:12",label:"POLITIQUE",region:"Lagunes",urgent:true,title:"Remaniement : le nouveau gouvernement attendu ce soir",text:"Le porte-parole annonce une communication imminente à l’issue du Conseil des ministres à Abidjan.",slug:"yamoussoukro-politiques-publiques"},
 {time:"15:58",label:"SPORT",title:"Éléphants : la liste des 26 dévoilée pour les éliminatoires",text:"Le sélectionneur intègre deux nouveaux joueurs évoluant en Europe.",slug:"bouake-basketball-economie-sport"},
 {time:"15:30",label:"BRVM",region:"Lagunes",title:"Clôture en hausse à la BRVM",text:"L’indice composite gagne 0,42 % porté par le compartiment bancaire.",slug:"brvm-pme-ivoiriennes-capital"},
 {time:"14:47",label:"SOCIÉTÉ",region:"Vallée du Bandama",title:"Bouaké : rentrée scolaire avancée dans plusieurs établissements",text:"Les autorités éducatives confirment le calendrier pour la région.",slug:"bouake-pme-industrie"},
 {time:"14:05",label:"AGRICULTURE",region:"Bas-Sassandra",title:"Cacao : ouverture de la campagne intermédiaire",text:"Les premiers prix bord-champ sont communiqués aux producteurs.",slug:"cacao-transformation-locale-san-pedro"},
 {time:"13:20",label:"CULTURE",region:"Comoé",urgent:false,title:"Grand-Bassam : le festival des arts ouvre ses portes",text:"Une programmation étoffée est annoncée pour l’édition de cette année.",slug:"grand-bassam-tourisme-culture"},
 {time:"12:36",label:"FAIT DIVERS",region:"Lagunes",title:"Trafic perturbé sur le pont HKB",text:"Un incident matériel ralentit la circulation en direction du Plateau.",slug:"metro-abidjan-mobilite-emplois"},
 {time:"11:52",label:"ÉNERGIE",region:"Savanes",title:"Nouveau champ solaire mis en service dans le nord",text:"L’installation doit renforcer l’alimentation de plusieurs localités.",slug:"energie-solaire-korhogo"},
 {time:"10:41",label:"ENTREPRISES",region:"Lagunes",title:"Une fintech ivoirienne lève des fonds régionaux",text:"L’opération vise l’expansion dans l’espace UEMOA.",slug:"startup-ivoiriennes-paiement"},
 {time:"09:15",label:"INTERNATIONAL",title:"UEMOA : réunion des ministres des Finances",text:"Les discussions portent sur la convergence budgétaire régionale.",slug:"abidjan-hub-financier-afrique-ouest"},
];
export const markets=[{name:"BRVM Composite",value:"335,18",change:"+0,42 %"},{name:"BRVM 30",value:"168,74",change:"+0,31 %"},{name:"EUR/XOF",value:"655,96",change:"0,00 %"},{name:"Cacao",value:"7 842 $",change:"+1,16 %"}];

export const brvmQuotes = [
 {symbol:"BRVM-C",name:"BRVM Composite",value:"335,18",change:"+0,42 %",trend:"up"},
 {symbol:"BRVM-30",name:"BRVM 30",value:"168,74",change:"+0,31 %",trend:"up"},
 {symbol:"PALMCI",name:"Palm Côte d’Ivoire",value:"7 850",change:"+1,95 %",trend:"up"},
 {symbol:"ORAC",name:"Orange Côte d’Ivoire",value:"13 400",change:"+0,75 %",trend:"up"},
 {symbol:"NSBC",name:"NSIA Banque CI",value:"6 150",change:"+0,49 %",trend:"up"},
 {symbol:"SOGC",name:"SOGB",value:"6 480",change:"−0,31 %",trend:"down"},
 {symbol:"SDCC",name:"SODECI",value:"5 300",change:"0,00 %",trend:"flat"},
];

export const events = [
 {day:"21",month:"AOÛT",city:"Abidjan",title:"Forum des décideurs et de l’investissement ivoirien",type:"Économie",image:"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=85"},
 {day:"04",month:"SEPT.",city:"Yamoussoukro",title:"Rencontres des politiques publiques territoriales",type:"Institutions",image:"https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1200&q=85"},
 {day:"18",month:"SEPT.",city:"San-Pédro",title:"Assises de la transformation locale du cacao",type:"Agriculture",image:"https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=1200&q=85"},
];

export const flashNews = [
 {time:"15:42",label:"BRVM",text:"Le compartiment actions termine la séance dans le vert à Abidjan."},
 {time:"15:18",label:"CACAO",text:"Les acteurs de la filière se réunissent à San-Pédro sur la transformation locale."},
 {time:"14:56",label:"ÉNERGIE",text:"Un nouveau programme solaire annoncé pour plusieurs localités du nord."},
 {time:"14:21",label:"ENTREPRISES",text:"Les PME ivoiriennes renforcent leurs investissements dans la logistique."},
 {time:"13:48",label:"POLITIQUE",text:"Le gouvernement présente un point d’étape sur la simplification administrative."},
 {time:"13:05",label:"AGRICULTURE",text:"La campagne d’anacarde entre dans une nouvelle phase de commercialisation."},
 {time:"12:32",label:"TRANSPORT",text:"Abidjan poursuit la modernisation de ses grands axes de mobilité."},
 {time:"11:47",label:"NUMÉRIQUE",text:"Les paiements de proximité progressent chez les commerçants indépendants."},
];

export const briefs = [
 {category:"Finance",region:"Lagunes",title:"Les banques accélèrent le financement des PME exportatrices"},
 {category:"Agriculture",region:"Sassandra-Marahoué",title:"Le café ivoirien cherche de nouveaux débouchés haut de gamme"},
 {category:"Industrie",region:"Bas-Sassandra",title:"La zone portuaire attire une nouvelle vague de projets"},
 {category:"Société",region:"Vallée du Bandama",title:"La formation professionnelle se rapproche des besoins des entreprises"},
 {category:"Énergie",region:"Savanes",title:"Les producteurs locaux misent sur l’irrigation solaire"},
 {category:"Culture",region:"Comoé",title:"Les industries créatives structurent leur modèle économique"},
 {category:"Politique publique",region:"Lacs",title:"Les collectivités renforcent le suivi des investissements locaux"},
 {category:"Commerce",region:"Montagnes",title:"Les coopératives développent de nouveaux circuits de distribution"},
 {category:"Sport business",region:"Lagunes",title:"Les clubs explorent de nouvelles sources de revenus"},
 {category:"Immobilier",region:"Lagunes",title:"Le logement intermédiaire reste au centre de la demande"},
 {category:"Mobilité",region:"Vallée du Bandama",title:"Le transport interurbain prépare sa transformation numérique"},
 {category:"Diaspora",region:"Lagunes",title:"Les investisseurs ivoiriens de l’étranger ciblent davantage les PME"},
];
