const countries: Record<string, {name:string; capital:string; stat:string; image:string; stories:string[]}> = {
  "cote-divoire": {name:"Côte d’Ivoire",capital:"Abidjan",stat:"+6,5 % de croissance",image:"https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1600&q=85",stories:["Abidjan accélère sa transformation en hub financier régional","Cacao : le nouveau rapport de force","Les PME ivoiriennes visent la sous-région"]},
  "senegal": {name:"Sénégal",capital:"Dakar",stat:"+7,1 % de croissance",image:"https://images.unsplash.com/photo-1598034609695-93063b47b1c6?auto=format&fit=crop&w=1600&q=85",stories:["Dakar mise sur l’industrie créative","Le port de Ndayane change d’échelle","La fintech sénégalaise accélère"]},
  "cameroun": {name:"Cameroun",capital:"Yaoundé",stat:"+4,8 % de croissance",image:"https://images.unsplash.com/photo-1523805009345-7448845a9e53?auto=format&fit=crop&w=1600&q=85",stories:["Douala réinvente sa logistique portuaire","Le café camerounais retrouve les marchés","Les startups de Yaoundé séduisent"]},
  "rdc": {name:"RDC",capital:"Kinshasa",stat:"105 M d’habitants",image:"https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1600&q=85",stories:["Le cuivre au centre de la transformation locale","Kinshasa attire les fonds d’infrastructure","Le mobile money change d’échelle"]},
  "mali": {name:"Mali",capital:"Bamako",stat:"22 M d’habitants",image:"https://images.unsplash.com/photo-1489493585363-d69421e0edd3?auto=format&fit=crop&w=1600&q=85",stories:["Les coopératives agricoles se modernisent","Bamako stimule l’entrepreneuriat local","Le solaire gagne les territoires"]},
  "burkina-faso": {name:"Burkina Faso",capital:"Ouagadougou",stat:"23 M d’habitants",image:"https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1600&q=85",stories:["Le coton prépare sa nouvelle saison","Les PME investissent dans la transformation","Ouagadougou développe ses services numériques"]},
  "france": {name:"France",capital:"Paris",stat:"2e économie de l’UE",image:"https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1600&q=85",stories:["Les entreprises françaises renforcent leurs liens africains","Paris accueille le sommet de l’investissement","La tech responsable gagne du terrain"]},
  "belgique": {name:"Belgique",capital:"Bruxelles",stat:"Cœur institutionnel européen",image:"https://images.unsplash.com/photo-1491557345352-5929e343eb89?auto=format&fit=crop&w=1600&q=85",stories:["Bruxelles redéfinit sa politique commerciale","Les fonds belges ciblent l’impact","La diaspora stimule les échanges"]},
  "canada": {name:"Canada",capital:"Ottawa",stat:"2 140 Md $ de PIB",image:"https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=1600&q=85",stories:["Le Canada mise sur les talents africains","Montréal accueille les fintechs francophones","Les minerais critiques au cœur des échanges"]},
};
export default async function CountryPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const c=countries[slug]||countries["cote-divoire"];return <main className="country-page"><header className="interior-header"><div className="shell interior-nav"><a href="/" className="mini-brand">L’Économiste<span>b</span></a><a href="/explorer">Toutes les éditions</a></div></header><section className="country-mast" style={{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.88),rgba(0,0,0,.2)),url(${c.image})`}}><div className="shell"><span>ÉDITION PAYS</span><h1>{c.name}</h1><p>{c.capital} • {c.stat}</p></div></section><nav className="country-nav shell"><a href="#une">À la une</a><a href="#economie">Économie</a><a href="#politique">Politique</a><a href="#business">Business</a><a href="#culture">Culture</a></nav><section className="shell country-content"><div className="country-lead"><span className="eyebrow">GRAND ANGLE</span><h2>{c.stories[0]}</h2><p>Les données, les acteurs et les décisions qui façonnent l’avenir économique du pays.</p><a href="/article">Lire l’analyse →</a></div><div className="country-list">{c.stories.slice(1).map((x,i)=><article key={x}><span>0{i+1}</span><div><small>{i?"BUSINESS":"ÉCONOMIE"}</small><h3><a href="/article">{x}</a></h3><p>Reportage et analyse de notre rédaction locale.</p></div></article>)}</div></section></main>}
